### ISSUE TITLE
Referenced v2 instead of master causes failure to GHA

### ISSUE THREAD

**Issue by nnacin** [chetan/invalidate-cloudfront-action#10]
Hello!

Recently we changed to use @v2 instead of @master when referencing this GHA but since then the workflow fails with this message `Error: Process completed with exit code 127.`.

Is there anything that can be done?
For now we updated it to use @master again.

Thanks!

**Comment by chetan** [comment]
Hey @nnacin. Thanks for the report.

I just tried testing with the `@v2` tag (you can see [the workflow here](https://github.com/chetan/invalidate-cloudfront-action/blob/test-tag/.github/workflows/tests.yml#L26)) and it ran ok. Can you share any more details of your workflow? You can also try enabling the debug flag which should produce more output:

```yaml
    - name: invalidate
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        DEBUG: "1"
```

It's entirely possible there's a bug in the path handling, I can try adding some more tests around that.

**Comment by nnacin** [comment]
Thanks for the quick answer. Used the debug flag but didnt more info.
This is the workflow:
```
 - name: Workflow name
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DEBUG: '1'
          DISTRIBUTION: DISTRIBUTION
          PATHS: PATHS
          AWS_REGION: AWS_REGION
          AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
```

The difference from your workflow is that we are using self-hosted runners. But it has Nodejs as dependancy.

**Comment by chetan** [comment]
Ah, ok, I think I know what is happening in that case. v1 (master branch) ran using a docker container while v2 is a simple bash script, however it also requires some common utilities provided by the github-hosted runners, namely `jq` and `aws`. (edit: bash exit code 127 generally means command not found, so it's likely one of these that's missing)

This is also one reason I didn't want to update the `master` branch to the latest version, as I feared there could be some large breaking changes and I had previously had `@master` as the default tag in the docs.  

I can add those as requirements to the README for v2 so that folks using self-hosted runners can install the necessary utils or add a step which does so.

**Comment by chetan** [comment]
Closing this out as I have not heard back. Feel free to reopen or file another issue if you still have problems.
